workflows:
  ios-release:
    name: iOS Release IPA
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - apple_id_login
        - apple_id_password
    scripts:
      - name: Install Flutter
        script: |
          git clone https://github.com/flutter/flutter.git -b stable $HOME/flutter
          export PATH="$PATH:$HOME/flutter/bin"
          flutter precache --android --ios
      - name: Get dependencies
        script: flutter pub get
      - name: Clean & build iOS IPA
        script: flutter build ipa --release --export-options-plist=ios/exportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcode_build/*.log
    publishing:
      email:
        recipients:
          - your.email@example.com
